#
# Copyright 2015-2023 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Spring Boot Support Samples

on: [push, pull_request]

permissions: read-all

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cache: [maven]
        distribution: ['zulu']
        java: [21, 25]
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
      max-parallel: 5
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name:  Setup Java ${{ matrix.java }} ${{ matrix.distribution }}
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
        with:
          cache: ${{ matrix.cache }}
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Test with Spring Boot Latest
        run: |
          ./mvnw package
          ./mybatis-spring-boot-samples/run_fatjars.sh
